# Generated by Django 2.1.2 on 2019-02-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190220_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch校区表', 'verbose_name_plural': 'Branch校区表'},
        ),
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name': 'ClassList班级信息表', 'verbose_name_plural': 'ClassList班级信息表'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course课程信息表', 'verbose_name_plural': 'Course课程信息表'},
        ),
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name': 'CourseRecord上课记录表', 'verbose_name_plural': 'CourseRecord上课记录表'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer客户信息表', 'verbose_name_plural': 'Customer客户信息表'},
        ),
        migrations.AlterModelOptions(
            name='customerfollowup',
            options={'verbose_name': 'CustomerFollowUp客户跟进表', 'verbose_name_plural': 'CustomerFollowUp客户跟进表'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Enrollment学员报名表', 'verbose_name_plural': 'Enrollment学员报名表'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu菜单表', 'verbose_name_plural': 'Menu菜单表'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment缴费记录表', 'verbose_name_plural': 'Payment缴费记录表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role角色信息表', 'verbose_name_plural': 'Role角色信息表'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name': 'StudyRecord学习成绩表', 'verbose_name_plural': 'StudyRecord学习成绩表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag标签', 'verbose_name_plural': 'Tag标签'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'UserProfile账号表', 'verbose_name_plural': 'UserProfile账号表'},
        ),
        migrations.AlterField(
            model_name='classlist',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结业日期'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='start_date',
            field=models.DateTimeField(verbose_name='开班日期'),
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上课日期'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='咨询日期'),
        ),
        migrations.AlterField(
            model_name='customerfollowup',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='跟进日期'),
        ),
    ]
