# Generated by Django 2.1.2 on 2019-02-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20190225_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id'], 'verbose_name': 'Customer客户信息表', 'verbose_name_plural': 'Customer客户信息表'},
        ),
    ]
