# Generated by Django 2.1.7 on 2019-03-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_userprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='role',
            new_name='roles',
        ),
    ]
