# Generated by Django 2.1.7 on 2019-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190320_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='contract_agreed',
            field=models.BooleanField(default=0, verbose_name='学员已同意合同'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='contract_approved',
            field=models.BooleanField(default=0, help_text='合同已审核', verbose_name='审批通过'),
        ),
    ]
