# Generated by Django 2.1.2 on 2019-03-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190228_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结业日期'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='start_date',
            field=models.DateField(verbose_name='开班日期'),
        ),
    ]
