# Generated by Django 2.1.7 on 2019-03-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20190324_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name': 'ClassList班级表', 'verbose_name_plural': 'ClassList班级表'},
        ),
    ]
