# Generated by Django 2.1.2 on 2019-03-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20190309_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名'),
        ),
    ]
