# Generated by Django 2.1.7 on 2019-03-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20190328_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='course',
        ),
    ]
