# Generated by Django 2.1.7 on 2019-03-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_remove_payment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.Course', verbose_name='所报课程'),
            preserve_default=False,
        ),
    ]
