# Generated by Django 2.1.7 on 2019-03-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20190313_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.IntegerField(choices=[(0, '未报名'), (1, '已报名')], default=0, help_text='选择客户此时的状态', verbose_name='报名状态'),
        ),
    ]
