# Generated by Django 2.1.7 on 2019-03-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20190330_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrecord',
            name='record',
            field=models.IntegerField(choices=[(0, '已签到'), (1, '迟到'), (2, '缺勤'), (3, '早退')], default=0, max_length=64, verbose_name='上课纪录'),
        ),
    ]
