# Generated by Django 2.1.7 on 2019-03-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20190330_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stu_account',
            field=models.ForeignKey(blank=True, help_text='只有学员报名后才能创建', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='学员账号'),
        ),
    ]
