# Generated by Django 2.1.2 on 2019-04-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_userprofile_stu_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrecord',
            name='record',
            field=models.IntegerField(choices=[(0, '已签到'), (1, '迟到'), (2, '缺勤'), (3, '早退')], default=0, verbose_name='上课纪录'),
        ),
    ]
