# Generated by Django 2.1.7 on 2019-04-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20190401_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyrecord',
            name='note',
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='评语'),
        ),
    ]
