# Generated by Django 2.1.2 on 2019-04-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20190401_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='avatar_data/img.jpg', upload_to='', verbose_name='头像'),
        ),
    ]
