# Generated by Django 2.1.2 on 2019-04-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_customer_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar_imgs/img.jpg', upload_to='', verbose_name='头像'),
        ),
    ]
