# Generated by Django 2.1.2 on 2019-04-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_auto_20190411_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='class_name',
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name='班级名称'),
        ),
    ]
