# Generated by Django 2.1.2 on 2019-04-11 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_classlist_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlist',
            name='class_name',
        ),
    ]
