# Generated by Django 2.1.2 on 2019-04-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_classlist_class_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id'], 'verbose_name': '客户信息', 'verbose_name_plural': '客户信息'},
        ),
    ]
